// <auto-generated />
using System;
using Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Sql.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Sql.Models.TripRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<DateTime>("DropoffDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("tpep_dropoff_datetime");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fare_amount");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<byte>("PassengerCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("passenger_count");

                    b.Property<DateTime>("PickupDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("tpep_pickup_datetime");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tip_amount");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float")
                        .HasColumnName("trip_distance");

                    b.HasKey("Id");

                    b.ToTable("TripRecord", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
